# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_app.gRPC.proto.mailer_pb2 as proto_dot_mailer__pb2


class MailerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_email = channel.unary_unary(
                '/Mailer/send_email',
                request_serializer=proto_dot_mailer__pb2.Text.SerializeToString,
                response_deserializer=proto_dot_mailer__pb2.Text.FromString,
                )


class MailerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_email(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MailerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_email': grpc.unary_unary_rpc_method_handler(
                    servicer.send_email,
                    request_deserializer=proto_dot_mailer__pb2.Text.FromString,
                    response_serializer=proto_dot_mailer__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Mailer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mailer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_email(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Mailer/send_email',
            proto_dot_mailer__pb2.Text.SerializeToString,
            proto_dot_mailer__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
