version: "3.9"
   
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ADMIN_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ADMIN_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ADMIN_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ADMIN_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_ADMIN_USERNAME:$MONGO_ADMIN_PASSWORD@mongo:27017/
  my_web_app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "80"
    command: gunicorn xsolla_backend_2021.wsgi:application --bind 0.0.0.0:80 --reload
    volumes:
      - .:/app

  web_server:
    build: ./nginx

    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - my_web_app
