# Generated by Django 3.2.4 on 2021-06-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_keeping_unit', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.producttype', verbose_name='Тип')),
            ],
        ),
    ]
