# Generated by Django 3.2.4 on 2021-08-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210622_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='e-mail')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.product', verbose_name='Продукт')),
            ],
        ),
    ]
