# Generated by Django 3.2.4 on 2021-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210622_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landing',
            field=models.CharField(default='https://vk.com', max_length=200, verbose_name='Лендинг'),
        ),
    ]
